### ISSUE TITLE
Dynamic linking error

### ISSUE THREAD

**Issue by inactive123** [libretro/mame#25]
@r-type 

The current version on the buildbot does not work. This is what I get upon trying to dynamically load the core in RetroArch-

RetroArch [ERROR] :: Failed to open libretro core: "/home/squarepusher/libretro-super/dist/unix/mame_libretro.so"
RetroArch [ERROR] :: Error(s): /home/squarepusher/libretro-super/dist/unix/mame_libretro.so: undefined symbol: _ZTI18segam1audio_device

**Comment by andres-asm** [comment]
Maybe your libc or whatever it's called is older than what's on the buildbot.
@Alcaro mentioned this could happen if the linux distro is too recent

**Comment by r-type** [comment]
Ok i cant look at until tomorrow.
Seem rax and segam1are not exported correctly.

**Comment by r-type** [comment]
it failed here exactly with the same error.
https://github.com/mamedev/mame/issues/2199

**Comment by r-type** [comment]
last merge should fix the issue .

**Comment by inactive123** [comment]
I still get 'No core' when I try to load the core on the buildbot (Load Core).

Try making sure there are no undefined symbols in your lib. There are some commandline switches you can specify for this.

**Comment by r-type** [comment]
does buildbot do a full clean build ? my own linux build works and i does not have  undefined symbol

**Comment by r-type** [comment]
the linux core provide by buildbot (05/04/2017 16:55) works for me .

**Comment by inactive123** [comment]
Yes that latest build seems to work for me. Thanks.

**Comment by inactive123** [comment]
Hi there @r-type,

seems to compile on most platforms except for OSX (MAME 0.185) -

http://p.0bl.net/33167 

Seems to be something related to pcap.
