### ISSUE TITLE
Game & Watch and Tiger Hanhelds are too slow (unless alternate render method is used)

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mame#288]
When loading those games normally, with their artwork, they run at 50-60% speed on my i5 4670.

In the standalone version they run fine.

The only way for these to run at full speed in RetroArch is to enable "alternate rendering method" and then choose a lower resolution, which completely mangles the prerendered LCD graphics of those devices.

**Comment by ghost** [comment]
I had a quick look at the code I know what the issue is ill try patch it this weekend but the whole video needs a little tlc. Thankfully the foundation is there to work from and should be fairly easy to patch so you can use it..

**Comment by ghost** [comment]
for what its worth the alternative render is actually the proper tenderer and the other one is the alternative . I have no idea why this is there but i fixed it up to what it should be doing incase someone uses it for switch res or something.

**Comment by Tasosgemah** [comment]
Alternate method worked because it let you choose a lower resolution. Otherwise it was just as slow.

**Comment by LibretroAdmin** [comment]
Will be awaiting a revised PR since there were some issues still with the last PR pointed out by @stuken.

**Comment by ghost** [comment]
only one mode is broke and it breaks the other its actually named backwards. If you choose alt on(the way mame does it) and reboot  it you should be fine. just use 640 or 800 i need to find out why this other mode is there at all.

**Comment by sonninnos** [comment]
Indeed the native resolution is rather large with these, so there isn't going to be a better solution for potatos than using a smaller fixed resolution with "alternative renderer". I'm not seeing any other limiting factors with performance, and also not any improvements either.

**Comment by Tasosgemah** [comment]
> Indeed the native resolution is rather large with these, so there isn't going to be a better solution for potatos than using a smaller fixed resolution with "alternative renderer". I'm not seeing any other limiting factors with performance, and also not any improvements either.

Any reason why the standalone runs them at full speed (on my system) but not the core?

**Comment by sonninnos** [comment]
Beats me, I tried a few and they run full speed.

And "standalone" basically is always using "alternative renderer".

**Comment by sonninnos** [comment]
Whoops, tried with actual required artwork and the situation changed dramatically. Indeed the resolution becomes way too massive, and surely there is a way and a reason to try limiting that regardless of the renderer.

Edit: Ok, managed to lower the default native resolution somewhat, so forcing alternative renderer is no longer necessary. Will do a bit more testing before pushing.
